### ISSUE TITLE
Improve output

### ISSUE THREAD

**Issue by jeroen** [r-hub/rhub-backend#11]
The [output](https://builder.r-hub.io/status/hunspell_2.1.tar.gz-aaa0a46d2c6d44085f15cc433a827fb9) currently makes it difficult to notice problems. Some suggestions:
- Make sections collapsible and automatically collapse all but the last section. I.e. on successful builds, hide sections `Starting Docker container` and `Installing package dependencies` and directly open the section with `Running R CMD check`.
- Highlight stderr in another color 
- A plain-text option which just returns the build log as a `text/plain` document instead of HTML.

**Comment by gaborcsardi** [comment]
:+1: Good, concrete suggestions!

> Make sections collapsible and automatically collapse all but the last section. I.e. on successful builds, hide sections Starting Docker container and Installing package dependencies and directly open the section with Running R CMD check.

Good idea. I didn't spend a lot of time on formatting the output, and also there is no JS there. I definitely need to improve it, and copy whatever is good from other CIs. This would be a good start.

> Highlight stderr in another color

Will try, but I am not sure if it is possible.

> A plain-text option which just returns the build log as a text/plain document instead of HTML.

https://builder.r-hub.io/status/original/hunspell_2.1.tar.gz-aaa0a46d2c6d44085f15cc433a827fb9

Also, I want to have a "default" view, basically only the things that the command line `rhub::check()` has, and an "expect" view that has everything.

**Comment by jeroen** [comment]
> https://builder.r-hub.io/status/original/hunspell_2.1.tar.gz-aaa0a46d2c6d44085f15cc433a827fb9

This is so much better than the HTML page. Maybe on the submit form, you can create a radiobox in which the user indicates if they want to be fowarded to the html or text ouput.

**Comment by gaborcsardi** [comment]
> Maybe on the submit form, you can create a radiobox in which the user indicates if they want to be fowarded to the html or text ouput.

Hmmm. I do not want to offer too many choices. :) How about a button on the HTML output that takes you to the text output. 

I guess advanced users would run the command line interface via the `rhub` R package, anyway. No? You would prefer the web interface?

**Comment by gaborcsardi** [comment]
Btw. have you tried the command line package at all?

**Comment by jeroen** [comment]
You mean your r client? Or is there a shell client?

**Comment by gaborcsardi** [comment]
Yes, R client. 

Although we could also have a simple shell client, basically you just need curl, really.

**Comment by jeroen** [comment]
Hmm I'm still getting `Stream error in the HTTP/2 framing layer`.

**Comment by gaborcsardi** [comment]
Interesting. `session_info`?

**Comment by jeroen** [comment]
<img width="897" alt="screen shot 2016-09-29 at 4 16 28 pm" src="https://cloud.githubusercontent.com/assets/216319/18957629/19f787ac-8660-11e6-856d-1133bde6d81e.png">

**Comment by jeroen** [comment]
I thought HTTP/2 was fixed on the server?

**Comment by gaborcsardi** [comment]
Oh, yeah, please `install.packages("rcmdcheck", type = "source")`.

As for HTTP/2, yes, I updated nginx, and that fixed both my Linux and Windows, both had been failing before. I haven't try OSX TBH. 

So OSX still fails for you? It is probably better to turn off http2 now in the client.

**Comment by jeroen** [comment]
Better figure out what's wrong with your server.... http/2 clients will soon become the norm.

**Comment by gaborcsardi** [comment]
THe server is just a stable nginx, so I suppose someone else will figure that out.

**Comment by gaborcsardi** [comment]
Or I just turn off http2 in the server. I really don't want to debug nginx, sorry.

**Comment by jeroen** [comment]
Yeah disabling HTTP/2 is fine. Just make sure it is not advertising HTTP/2 support if there is something in the stack that does not support that.

**Comment by gaborcsardi** [comment]
Just tried 

```
brew install curl --with-nghttp2
brew link --force curl

curl -v https://builder.r-hub.io/api/check/validate_email \
  -H 'Content-Type: application/json' \
  -d '{"email":"jeroenooms@gmail.com"}'
```

on OSX and it worked fine, actually.

**Comment by jeroen** [comment]
Yeah but other API's still fail? Does `check()` work now?

**Comment by jeroen** [comment]
<img width="570" alt="screen shot 2016-09-29 at 4 24 00 pm" src="https://cloud.githubusercontent.com/assets/216319/18957919/27138b42-8661-11e6-8ff7-4e9a47540dc7.png">

**Comment by jeroen** [comment]
This is almost getting there. Maybe print the status URL somewhere so that I can check the logs see why it fails to install.

<img width="573" alt="screen shot 2016-09-29 at 4 24 40 pm" src="https://cloud.githubusercontent.com/assets/216319/18957958/433a13e0-8661-11e6-9e2c-3622607dcf7a.png">

**Comment by gaborcsardi** [comment]
There is a status URL, on the top. It should be there at least.

**Comment by gaborcsardi** [comment]
So what was the http/2 issue?

**Comment by jeroen** [comment]
Ah right I didn't notice that URL. I don't know what the HTTP/2 issue is. it just gives this same error now when uploading the package...

**Comment by gaborcsardi** [comment]
Maybe you have a devel version of the curl package? 

I never had any issues on OSX....

**Comment by jeroen** [comment]
Yes that is correct, I run the devel version of `curl`. But that should still work :)

**Comment by gaborcsardi** [comment]
Btw. tell Rstudio to support colored output, and then it will look like this:
<img width="1013" alt="screen shot 2016-09-29 at 3 31 20 pm" src="https://cloud.githubusercontent.com/assets/660288/18958229/e0a2f37a-8659-11e6-9f4d-992d0e53277d.png">

**Comment by jeroen** [comment]
How do I do that?

**Comment by gaborcsardi** [comment]
Sorry, I mean, tell the Rstudio people to add support for it. :) I told them a couple times already..... there is also an open issue somewhere, and Kevin knows about it.

**Comment by jeroen** [comment]
Ah right. I think that's difficult for them to implement with the GWT frontend...

**Comment by jeroen** [comment]
BTW my mailbox is getting filled up with these huge build logs. I would really prefer an email with a link to the build log instead.

**Comment by gaborcsardi** [comment]
I don't think it is difficult. They already color stuff, would just need to filter the console output coming from R. But yeah, probably not 10 minutes, frankly, I have no idea.

Another way would be to show it in the viewer, but that's kinda gross.

Re: emails. yes, the emails are horrible. Bigger things on the todo list:
- release `rhub`
- add more windows versions
- fix the emails

About next week I hope.

**Comment by gaborcsardi** [comment]
But sending a link is a good idea as a quick fix. 

My only issue is that the link is only valid for ~3days. But that's probably OK.

**Comment by jeroen** [comment]
Yeah that's fine. The CRAN win builder links are valid for 48 hours.

**Comment by gaborcsardi** [comment]
Btw. if `curl` could do the async downloads, then I could have a much better spinner / progress bar. :)

**Comment by jeroen** [comment]
See https://github.com/gaborcsardi/rhub/commit/3aa9fcaa2b273a4a92fb0714f7c8a434d9be375c. This is pretty hacky so I understand if you don't want to go there, but it is certainly convenient.

**Comment by jeroen** [comment]
Oops wrong discussion,
